/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as SlettKontoRouteImport } from './routes/slett-konto'
import { Route as ApiAddressesRouteImport } from './routes/api.addresses'
import { Route as ApiSendRouteImport } from './routes/api.send'
import { Route as RestauranterIndexRouteImport } from './routes/restauranter.index'
import { Route as RestauranterSlugRouteImport } from './routes/restauranter.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const SlettKontoRoute = SlettKontoRouteImport.update({
  id: '/slett-konto',
  path: '/slett-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressesRoute = ApiAddressesRouteImport.update({
  id: '/api/addresses',
  path: '/api/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranterIndexRoute = RestauranterIndexRouteImport.update({
  id: '/restauranter/',
  path: '/restauranter/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranterSlugRoute = RestauranterSlugRouteImport.update({
  id: '/restauranter/$slug',
  path: '/restauranter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/slett-konto': typeof SlettKontoRoute
  '/api/addresses': typeof ApiAddressesRoute
  '/api/send': typeof ApiSendRoute
  '/restauranter/$slug': typeof RestauranterSlugRoute
  '/restauranter/': typeof RestauranterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/slett-konto': typeof SlettKontoRoute
  '/api/addresses': typeof ApiAddressesRoute
  '/api/send': typeof ApiSendRoute
  '/restauranter/$slug': typeof RestauranterSlugRoute
  '/restauranter': typeof RestauranterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/slett-konto': typeof SlettKontoRoute
  '/api/addresses': typeof ApiAddressesRoute
  '/api/send': typeof ApiSendRoute
  '/restauranter/$slug': typeof RestauranterSlugRoute
  '/restauranter/': typeof RestauranterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/om-oss'
    | '/personvern'
    | '/slett-konto'
    | '/api/addresses'
    | '/api/send'
    | '/restauranter/$slug'
    | '/restauranter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/om-oss'
    | '/personvern'
    | '/slett-konto'
    | '/api/addresses'
    | '/api/send'
    | '/restauranter/$slug'
    | '/restauranter'
  id:
    | '__root__'
    | '/'
    | '/om-oss'
    | '/personvern'
    | '/slett-konto'
    | '/api/addresses'
    | '/api/send'
    | '/restauranter/$slug'
    | '/restauranter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OmOssRoute: typeof OmOssRoute
  PersonvernRoute: typeof PersonvernRoute
  SlettKontoRoute: typeof SlettKontoRoute
  ApiAddressesRoute: typeof ApiAddressesRoute
  ApiSendRoute: typeof ApiSendRoute
  RestauranterSlugRoute: typeof RestauranterSlugRoute
  RestauranterIndexRoute: typeof RestauranterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slett-konto': {
      id: '/slett-konto'
      path: '/slett-konto'
      fullPath: '/slett-konto'
      preLoaderRoute: typeof SlettKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/addresses': {
      id: '/api/addresses'
      path: '/api/addresses'
      fullPath: '/api/addresses'
      preLoaderRoute: typeof ApiAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restauranter/': {
      id: '/restauranter/'
      path: '/restauranter'
      fullPath: '/restauranter/'
      preLoaderRoute: typeof RestauranterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restauranter/$slug': {
      id: '/restauranter/$slug'
      path: '/restauranter/$slug'
      fullPath: '/restauranter/$slug'
      preLoaderRoute: typeof RestauranterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OmOssRoute: OmOssRoute,
  PersonvernRoute: PersonvernRoute,
  SlettKontoRoute: SlettKontoRoute,
  ApiAddressesRoute: ApiAddressesRoute,
  ApiSendRoute: ApiSendRoute,
  RestauranterSlugRoute: RestauranterSlugRoute,
  RestauranterIndexRoute: RestauranterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
